services:
  deeppresenter-host:
    build:
      context: .
      dockerfile: deeppresenter/docker/Host.Dockerfile
      args:
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
        no_proxy: ${no_proxy:-}
    image: deeppresenter-host
    container_name: deeppresenter-host
    ports:
      - "7861:7861"
    environment:
      DEEPPRESENTER_HOST_WORKSPACE_BASE: ${PWD}/workspace
      DEEPPRESENTER_WORKSPACE_BASE: /opt/workspace
      DEEPPRESENTER_LOG_LEVEL: 0 # 0: debug, 10: info, 20: warning
    volumes:
      - ./workspace:/opt/workspace
      - ./deeppresenter:/usr/src/pptagent/deeppresenter
      - /usr/src/pptagent/deeppresenter/html2pptx/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - $HOME/.cache/modelscope:/root/.cache/modelscope

volumes:
  deeppresenter_workspace: